use_ddp: false   # whether to use DataDistributedParallel, for multi-gpus.
port:   12345 # the port for the DataDistributedParallel training.

# resume: /DATA/bvac/personal/reserach/font_gen/mxfont/result_ch_korean_eng/checkpoints/040000.pth
work_dir: ./result   # the directory to save checkpoints, validation images, and the log.

decomposition: data/chn_decomposition.json   # path to the "decomposition rule" file.
primals: data/chn_primals.json   # path to the "primals" file.

dset:   # leave blank
  train:   # leave blank
    data_dir: data/ttfs/train   # path to .ttf files for the training
  val:   # leave blank
    data_dir: data/ttfs/val   # path to .ttf files for the validation
    source_font: data/ttfs/val/MaShanZheng-Regular.ttf   # path to the .ttf file used as the source font during the validation

print_freq: 500 #1000
val_freq: 500 # 100000
save_freq: 500 # 50000
batch_size: 5 #8
max_iter: 10000 #800000